-- MockPanel Database Schema (Simplified)
-- Run this in Supabase SQL Editor

-- 1. Table for Interview Sessions
CREATE TABLE IF NOT EXISTS interviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  user_id UUID, -- Links to Supabase Auth
  domain TEXT NOT NULL, -- e.g., UPSC, Software Engineer
  settings JSONB DEFAULT '{}', -- Added for API compatibility
  difficulty TEXT,
  language TEXT DEFAULT 'English',
  status TEXT DEFAULT 'pending', -- pending, active, completed
  transcript JSONB DEFAULT '[]',
  feedback JSONB
);

-- 2. Table for Interview Messages (Optional for deep history)
CREATE TABLE IF NOT EXISTS interview_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID REFERENCES interviews(id) ON DELETE CASCADE,
  role TEXT, -- 'assistant' or 'user'
  content TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Add settings column if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'interviews' AND column_name = 'settings') THEN
        ALTER TABLE interviews ADD COLUMN settings JSONB DEFAULT '{}';
    END IF;
END $$;

-- Row Level Security
ALTER TABLE interviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE interview_messages ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist and recreate
DROP POLICY IF EXISTS "Users can view own interviews" ON interviews;
DROP POLICY IF EXISTS "Users can create own interviews" ON interviews;
DROP POLICY IF EXISTS "Users can update own interviews" ON interviews;
DROP POLICY IF EXISTS "Users can view messages for own interviews" ON interview_messages;
DROP POLICY IF EXISTS "Users can create messages for own interviews" ON interview_messages;

-- Policies
CREATE POLICY "Users can view own interviews" ON interviews
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create own interviews" ON interviews
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own interviews" ON interviews
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can view messages for own interviews" ON interview_messages
    FOR SELECT USING (
        auth.uid() = (SELECT user_id FROM interviews WHERE id = session_id)
    );

CREATE POLICY "Users can create messages for own interviews" ON interview_messages
    FOR INSERT WITH CHECK (
        auth.uid() = (SELECT user_id FROM interviews WHERE id = session_id)
    );

-- 3. Table for Final Analytics (Generated by background workers)
CREATE TABLE IF NOT EXISTS final_analytics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID REFERENCES interviews(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT now(),
  technical_score INTEGER CHECK (technical_score >= 0 AND technical_score <= 100),
  communication_score INTEGER CHECK (communication_score >= 0 AND communication_score <= 100),
  confidence_score INTEGER CHECK (confidence_score >= 0 AND confidence_score <= 100),
  ethical_integrity_score INTEGER CHECK (ethical_integrity_score >= 0 AND ethical_integrity_score <= 100),
  overall_score INTEGER CHECK (overall_score >= 0 AND overall_score <= 100),
  strengths TEXT[],
  weaknesses TEXT[],
  recommendations TEXT[],
  question_analysis JSONB DEFAULT '[]',
  transcript TEXT,
  total_questions INTEGER DEFAULT 0,
  total_user_responses INTEGER DEFAULT 0,
  status TEXT DEFAULT 'processing'
);

-- Enable RLS for analytics
ALTER TABLE final_analytics ENABLE ROW LEVEL SECURITY;

-- Analytics policies
DROP POLICY IF EXISTS "Users can view own analytics" ON final_analytics;
CREATE POLICY "Users can view own analytics" ON final_analytics
    FOR SELECT USING (
        auth.uid() = (SELECT user_id FROM interviews WHERE id = session_id)
    );

-- Performance Indexes (Critical for Production)
-- Sessions table indexes
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON interviews(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_status ON interviews(status);
CREATE INDEX IF NOT EXISTS idx_sessions_domain ON interviews(domain);

-- Messages table indexes
CREATE INDEX IF NOT EXISTS idx_messages_session_id ON interview_messages(session_id, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_messages_role ON interview_messages(role);

-- Analytics table indexes
CREATE INDEX IF NOT EXISTS idx_analytics_session ON final_analytics(session_id);

-- Full-text search index for transcripts (future feature)
CREATE INDEX IF NOT EXISTS idx_messages_fts ON interview_messages USING gin(to_tsvector('english', content));
CREATE INDEX IF NOT EXISTS idx_analytics_transcript_fts ON final_analytics USING gin(to_tsvector('english', transcript));